test_sample = {
    'Marital status': 1,
    'Application mode': 8,
    'Application order': 5,
    'Course': 2,
    'Daytime/evening attendance': 1,
    'Previous qualification': 1,
    'Nacionality': 1,
    "Mother's qualification": 13,
    "Father's qualification": 10,
    "Mother's occupation": 6,
    "Father's occupation": 10,
    'Displaced': 1,
    'Educational special needs': 0,
    'Debtor': 0,
    'Tuition fees up to date': 1,
    'Gender': 1,
    'Scholarship holder': 0,
    'Age at enrollment': 20,
    'International': 0,
    'Curricular units 1st sem (credited)': 0,
    'Curricular units 1st sem (enrolled)': 0,
    'Curricular units 1st sem (evaluations)': 0,
    'Curricular units 1st sem (approved)': 0,
    'Curricular units 1st sem (grade)': 0.0,
    'Curricular units 1st sem (without evaluations)': 0,
    'Curricular units 2nd sem (credited)': 0,
    'Curricular units 2nd sem (enrolled)': 0,
    'Curricular units 2nd sem (evaluations)': 0,
    'Curricular units 2nd sem (approved)': 0,
    'Curricular units 2nd sem (grade)': 0.0,
    'Curricular units 2nd sem (without evaluations)': 0,
    'Unemployment rate': 10.8,
    'Inflation rate': 1.4,
    'GDP': 1.74,
    'Target': 'Dropout'
}
